export const Medications = [
  { id: 10, name: 'Medication 10', category: 1 },
  { id: 11, name: 'Medication 11', category: 1 },
  { id: 12, name: 'Medication 12', category: 1 },
  { id: 13, name: 'Medication 13', category: 1 },
  { id: 14, name: 'Medication 14', category: 1 },
  { id: 15, name: 'Medication 15', category: 1 },
  { id: 16, name: 'Medication 16', category: 1 },
  { id: 17, name: 'Medication 17', category: 1 },
  { id: 18, name: 'Medication 18', category: 1 },
  { id: 19, name: 'Medication 19', category: 1 },

  { id: 20, name: 'Medication 20', category: 2 },
  { id: 21, name: 'Medication 21', category: 2 },
  { id: 22, name: 'Medication 22', category: 2 },
  { id: 23, name: 'Medication 23', category: 2 },
  { id: 24, name: 'Medication 24', category: 2 },
  { id: 25, name: 'Medication 25', category: 2 },
  { id: 26, name: 'Medication 26', category: 2 },
  { id: 27, name: 'Medication 27', category: 2 },
  { id: 28, name: 'Medication 28', category: 2 },
  { id: 29, name: 'Medication 29', category: 2 },

  { id: 30, name: 'Medication 30', category: 3 },
  { id: 31, name: 'Medication 31', category: 3 },
  { id: 32, name: 'Medication 32', category: 3 },
  { id: 33, name: 'Medication 33', category: 3 },
  { id: 34, name: 'Medication 34', category: 3 },
  { id: 35, name: 'Medication 35', category: 3 },
  { id: 36, name: 'Medication 36', category: 3 },
  { id: 37, name: 'Medication 37', category: 3 },
  { id: 38, name: 'Medication 38', category: 3 },
  { id: 39, name: 'Medication 39', category: 3 },

  { id: 30, name: 'Medication 30', category: 3 },
  { id: 31, name: 'Medication 31', category: 3 },
  { id: 32, name: 'Medication 32', category: 3 },
  { id: 33, name: 'Medication 33', category: 3 },
  { id: 34, name: 'Medication 34', category: 3 },
  { id: 35, name: 'Medication 35', category: 3 },
  { id: 36, name: 'Medication 36', category: 3 },
  { id: 37, name: 'Medication 37', category: 3 },
  { id: 38, name: 'Medication 38', category: 3 },
  { id: 39, name: 'Medication 39', category: 3 },
]
