export const medications = [
  { id: 10, name: 'Medication 10', categoryId: 1 },
  { id: 11, name: 'Medication 11', categoryId: 1 },
  { id: 12, name: 'Medication 12', categoryId: 1 },
  { id: 13, name: 'Medication 13', categoryId: 1 },
  { id: 14, name: 'Medication 14', categoryId: 1 },
  { id: 15, name: 'Medication 15', categoryId: 1 },
  { id: 16, name: 'Medication 16', categoryId: 1 },
  { id: 17, name: 'Medication 17', categoryId: 1 },
  { id: 18, name: 'Medication 18', categoryId: 1 },
  { id: 19, name: 'Medication 19', categoryId: 1 },

  { id: 20, name: 'Medication 20', categoryId: 2 },
  { id: 21, name: 'Medication 21', categoryId: 2 },
  { id: 22, name: 'Medication 22', categoryId: 2 },
  { id: 23, name: 'Medication 23', categoryId: 2 },
  { id: 24, name: 'Medication 24', categoryId: 2 },
  { id: 25, name: 'Medication 25', categoryId: 2 },
  { id: 26, name: 'Medication 26', categoryId: 2 },
  { id: 27, name: 'Medication 27', categoryId: 2 },
  { id: 28, name: 'Medication 28', categoryId: 2 },
  { id: 29, name: 'Medication 29', categoryId: 2 },

  { id: 30, name: 'Medication 30', categoryId: 3 },
  { id: 31, name: 'Medication 31', categoryId: 3 },
  { id: 32, name: 'Medication 32', categoryId: 3 },
  { id: 33, name: 'Medication 33', categoryId: 3 },
  { id: 34, name: 'Medication 34', categoryId: 3 },
  { id: 35, name: 'Medication 35', categoryId: 3 },
  { id: 36, name: 'Medication 36', categoryId: 3 },
  { id: 37, name: 'Medication 37', categoryId: 3 },
  { id: 38, name: 'Medication 38', categoryId: 3 },
  { id: 39, name: 'Medication 39', categoryId: 3 },

  { id: 40, name: 'Medication 40', categoryId: 4 },
  { id: 41, name: 'Medication 41', categoryId: 4 },
  { id: 42, name: 'Medication 42', categoryId: 4 },
  { id: 43, name: 'Medication 43', categoryId: 4 },
  { id: 44, name: 'Medication 44', categoryId: 4 },
  { id: 45, name: 'Medication 45', categoryId: 4 },
  { id: 46, name: 'Medication 46', categoryId: 4 },
  { id: 47, name: 'Medication 47', categoryId: 4 },
  { id: 48, name: 'Medication 48', categoryId: 4 },
  { id: 49, name: 'Medication 49', categoryId: 4 },
]
